Add swagger section
KevinTemes/tech-guides pull request #2
Opened 2019-10-31 23:31 UTC by darkBasic666

## Summary
Add API documentation section

2019-11-01 16:22 UTC, icoluccio requested changes

2019-11-01 16:22 UTC, icoluccio commented on backend/backend-standard-and-best-practices.md
> +There are lots of different tools in the market to document APIs. Here in Wolox we decided to use Openpi 3 (A.K.A Swagger) as a standard documentation tool in all of our techs. The reasons behind thi
Openapi*

2019-11-01 16:22 UTC, icoluccio commented on backend/backend-standard-and-best-practices.md
> +* **Maintainable and easily extendable**: Swagger permit use constants file/s from your API.
allows using?

2019-11-01 16:22 UTC, icoluccio commented on backend/backend-standard-and-best-practices.md
> +* **Intuitive and easy to use interactive UI**: Swagger up a view where show how to do a request and how to response the API.
I think you missed a few words here

![](http://cdn-webimages.wimages.net/04f1b5454338612504654a464c6f92ad122856-wm.jpg?v=3)

2019-11-14 14:11 UTC, KevinTemes approved these changes

2019-11-14 15:55 UTC, zeminlu requested changes
Just a couple of changes and all set!

2019-11-14 15:55 UTC, zeminlu commented on backend/backend-standard-and-best-practices.md
> +* **Quick to use**: The properties that you need to complete in every endpoint are always the same and there are only a few. You can also frequently reuse components and the generic information is si
you need to complete -> you  need to fill
simple to complete -> simple to provide

2019-11-14 15:55 UTC, zeminlu commented on backend/backend-standard-and-best-practices.md
> +* **Intuitive and easy to use interactive UI**: Swagger uses a GUI to show the user how to make requests to the API and what responses will be like.
will be like -> will look like

2019-11-14 15:55 UTC, zeminlu commented on backend/backend-standard-and-best-practices.md
> +* **Maintainable and easily extendable**: Swagger allows using constants file/s from your API.
file/s -> files

2019-11-27 16:43 UTC, zeminlu approved these changes

2019-11-27 16:44 UTC, icoluccio approved these changes

2019-11-27 16:47 UTC, merged