Made some modifications based on feedback
KevinTemes/tech-guides pull request #6
Opened 2019-11-29 18:59 UTC by KevinTemes

**Remember** to use the [corresponding tag](../README.md#contributing) in this PR's title.

## Summary

* Added disclaimer at document introduction;
* Removed offset paramenter from `_link` parameters in pagination example;
* Removed `status_code` parameter from error response example, to avoid redundancy;
* Modified example `code` parameters in error response to avoid confusion with HTTP status codes;
* Added disclaimer in error response clarifications.

2019-11-29 19:47 UTC, icoluccio approved these changes

2019-11-29 19:47 UTC, icoluccio commented on backend/backend-standard-and-best-practices.md
> +The purpose of this document is to present the standards we use in Wolox to work with APIs in the backend department. This standards are simply suggestions and guidelines, and depending on the case,
```suggestion
The purpose of this document is to present the standards we use in Wolox to work with APIs in the backend department. This standards are simply suggestions and guidelines, and depending on the case, they can be adapted if necessary.
```

2019-11-29 20:00 UTC, zeminlu requested changes
Excelent! I only found what icoluccio mentione to change and should be ready to go :)

2019-11-29 20:00 UTC, zeminlu commented on backend/backend-standard-and-best-practices.md
> +The purpose of this document is to present the standards we use in Wolox to work with APIs in the backend department. This standards are simply suggestions and guidelines, and depending on the case,
I like this suggestion :)

2019-12-02 15:56 UTC, zeminlu approved these changes

2019-12-02 16:00 UTC, merged